url: https://lukeabr.github.io

# Site settings
title: Luke Abram
description: "Luke Abram's online music portfolio."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCsu40B39aOCFuMZoWpygKzw
  - title: spotify
    url: https://open.spotify.com/artist/4oexwtiZ1sP2PHUU5cigcR?si=3clfxLOHTe6A5XHs93rIiQ
  - title: soundcloud
    url: https://soundcloud.com/luke-abram-957459838

# Postal address (add as many lines as necessary)
address:
  - line: Sterling VA 20165

# Build settings
markdown: kramdown
permalink: pretty
